# When set to false, ignores files with "GENERATED" header, similar to golint
ignoreGeneratedHeader = false

# Sets the default severity to "warning"
severity = "warning"

# Sets the default failure confidence. This means that linting errors
# with less than 0.8 confidence will be ignored.
confidence = 0.8

# Sets the error code for failures with severity "error"
errorCode = 1

# Sets the error code for failures with severity "warning"
warningCode = 1

enableAllRules = true

# Configuration of the `cyclomatic` rule. Here we specify that
# the rule should fail if it detects code with higher complexity than 10.
# [rule.cyclomatic]
#   arguments = [10]

# Sets the severity of the `package-comments` rule to "error".

# Disabled rules
[rule.package-comments]
    Disabled = true
[rule.banned-characters]
    Disabled = true
[rule.file-header]
    Disabled = true
[rule.max-public-structs]
    Disabled = true
[rule.function-length]
    Disabled = true
[rule.blank-imports]
    Disabled = true

# Temp disabled rules
[rule.add-constant]
    Disabled = true
[rule.line-length-limit]
    Disabled = true
#    Arguments = [80]
[rule.cognitive-complexity]
    Disabled = true
[rule.range-val-address]
    Disabled = true
#    Arguments = [7]
[rule.flag-parameter]
    Disabled = true
[rule.import-shadowing]
    Disabled = true
[rule.unused-parameter]
    Disabled = true
[rule.unused-receiver]
    Disabled = true
[rule.function-result-limit]
    Disabled = true
#   Arguments = [4]
[rule.get-return]
    Disabled = true
[rule.deep-exit]
    Disabled = true
[rule.nested-structs]
    Disabled = true
[rule.bare-return]
    Disabled = true
[rule.empty-lines]
    Disabled = true
[rule.unhandled-error]
    Disabled = true
[rule.confusing-naming]
    Disabled = true
[rule.early-return]
    Disabled = true
[rule.comment-spacings]
    Disabled = true
[rule.redundant-import-alias]
    Disabled = true


# Rule tunning
[rule.argument-limit]
    Arguments = [9]
[rule.cyclomatic]
    Arguments = [80]
